export const desktopQuotes = [
    { "text": "Sichqonchani sekinroq bosing, u sizga dushman emas." },
    { "text": "Klaviatura chidamli, lekin sizning mushtingiz og‘irroq." },
    { "text": "Enter tugmasini boshi aylanib qoldi." },
    { "text": "Monitorni artib turing, chang bosibdi-ku, og‘ayni." },
    { "text": "Tizim qotdi deb asabiylashmang, bir piyola choy iching." },
    { "text": "Bu CS:GO emas, o‘q uzmang, shunchaki hisobotni bosing." },
    { "text": "Logotipga tikilmang, ish o‘zini-o‘zi qilmaydi." },
    { "text": "Sizning parolingiz '12345' emasmi mabodo?" },
    { "text": "Kursorni qimirlatish — bu sport emas." },
    { "text": "Yana bir marta bossangiz, tizim o‘zini portlatadi." },
    { "text": "Server tutayapti, o‘t o‘chirgichni tayyorlang." },
    { "text": "Buni IT bo‘limiga aytmang, o‘zimiz hal qilamiz." },
    { "text": "Siz hakersiz shekilli, buncha ko‘p bosasiz?" },
    { "text": "Qo‘llaringiz moy bo‘lsa, klaviaturaga tegmang." },
    { "text": "Space tugmasi dam olishni xohlaydi." },
    { "text": "Bu tugma bosilmaydi, bu shunchaki rasm." },
    { "text": "Escape tugmasi muammolardan qochishga yordam bermaydi." },
    { "text": "Sichqonchangizning g‘ildiragi erib ketdi." },
    { "text": "Ctrl+Alt+Delete hayotda ishlamaydi, aka." },
    { "text": "Kompyuterni o‘chirib-yoqish — eng zo‘r yechim." },
    { "text": "Sizning brauzeringizda juda ko‘p ochiq sahifa bor." },
    { "text": "VPN yoqilganmi? Sekin ishlayapti." },
    { "text": "Tizimga kirish xuddi xotinning telefonini ochishdek qiyin." },
    { "text": "Sizning IP manzilingizni bilamiz (hazil)." },
    { "text": "USB fleshkani xavfsiz chiqardingizmi?" },
    { "text": "Monitorga yaqin o‘tirmang, ko‘z nuri kerak." },
    { "text": "Bu xatolik emas, bu tizimning xarakteri." },
    { "text": "Sizning so‘rovingiz navbatda turibdi, xuddi zapravkada." },
    { "text": "Texnika temir, siz esa jonsiz. Asabni asrang." },
    { "text": "Printer qog‘oz chaynab yubordi, yana." },
    { "text": "Kabelni tepib yubormang, internet o‘chadi." },
    { "text": "Wi-Fi parolini qo‘shningizga bermang." },
    { "text": "Sizning kompyuteringiz nafaqaga chiqmoqchi." },
    { "text": "Dasturchilar bu joyda nima deb o‘ylagan ekan-a?" },
    { "text": "Xatolik oynasini yopib qo‘yavering, hech kim ko‘rmadi." },

    { "text": "Xush kelibsiz, {name}. Bugun kayfiyatlar qalay, komandir?" },
    { "text": "{name}, bugun osh bormi yoki yana tort yeymizmi?" },
    { "text": "{name}, bu raqamlar to‘g‘rimi yoki 'taxminan' yozdingizmi?" },
    { "text": "{name}, mashinani moyini almashtirdingizmi?" },
    { "text": "{name}, bugun futbol bor, ishni vaqtliroq tugatamiz." },
    { "text": "{name}, ayolingiz qo‘ng‘iroq qilyapti, go‘shakni ko‘taring, qo‘rqmang." },
    { "text": "{name}, omborda 'nedostacha' yo‘qmi? Ko‘zimga qarang." },
    { "text": "{name}, bugun galstuk taqmabsiz, erkinlikmi?" },
    { "text": "{name}, sizsiz bu ofis xuddi benzinsiz mashinadek." },
    { "text": "{name}, kassani yopib, choyxonaga ketdikmi?" },
    { "text": "{name}, sochingiz oqaribdi, bu tizimdanmi?" },
    { "text": "{name}, bugun yuzingizdan nur yog‘ilyapti, oylik tushdimi?" },
    { "text": "{name}, qorin ochdi, somsa buyurtma qilaylik." },
    { "text": "{name}, siz bu yerni 'krishasi'siz." },
    { "text": "{name}, bu hisobotni buxgalter ko‘rmasin." },
    { "text": "{name}, qarz daftari to‘lib ketdi, nima qilamiz?" },
    { "text": "{name}, yana sigaret chekkani ketyapsizmi?" },
    { "text": "{name}, telefonni ovozsizga qo‘ying, majlisdamiz." },
    { "text": "{name}, sizga bitta 'Spark' sovg‘a qilish kerak (hazil)." },
    { "text": "{name}, bugun kim bilan 'razbor' qilamiz?" },
    { "text": "{name}, asabni buzishga arzimaydi." },
    { "text": "{name}, siz strategsiz, bu yerda taktika kerak." },
    { "text": "{name}, charchadingizmi? Men ham." },
    { "text": "{name}, stulni sindirib qo‘ymang." },
    { "text": "{name}, bugun formadasiz-ku!" },

    { "text": "Omborda tartib — buvada tartib." },
    { "text": "Sichqonlar unni yeb qo‘ymadimi? Tekshiring." },
    { "text": "Yuk ko‘tarishda belni ehtiyot qiling, aka." },
    { "text": "Inventarizatsiya — bu erkak kishining ishi." },
    { "text": "Qoplar og‘ir, lekin bizning irodamiz og‘irroq." },
    { "text": "Un changi — bu bizning upamiz." },
    { "text": "Yog‘ bochkasi teshildimi? Kim qildi?" },
    { "text": "Omborchi uxlasa, 'nedostacha' uyg‘onadi." },
    { "text": "Gruzchiklar qochib ketdi, o‘zingiz tushirasiz endi." },
    { "text": "Muddati o‘tgan tovarni dushmanga beramiz." },
    { "text": "Qoldiq chiqmayapti, kalkulyator buzilganmi?" },
    { "text": "Ombor kalitini yo‘qotmang, bu hayot-mamot masalasi." },
    { "text": "Mahsulotni 'spisat' qilishga shoshilmang." },
    { "text": "Kalamushlarga qopqon qo‘ying." },
    { "text": "Omborda sigaret chekmang, portlaymiz." },
    { "text": "Yuk mashinasi keldi, darvozani oching." },
    { "text": "Palletlarni to‘g‘ri joylashtiring, Tetris o‘ynagandek." },
    { "text": "Sovutgich ishlamayapti, usta chaqiring." },
    { "text": "Ombor sovuq, issiqroq kiyining." },
    { "text": "Bu qutida nima bor? Oltinmi?" },
    { "text": "Tara (idish) hisobi — pul hisobi." },
    { "text": "Qopni yelkalash — sportzalga borish shart emas." },
    { "text": "Hamma narsa joyida bo‘lishi shart, biz nemis emasmiz, lekin..." },
    { "text": "Qog‘ozda bor, omborda yo‘q — bu fokus." },
    { "text": "Shakar nam bo‘lib qoldi, qayerdan suv oqyapti?" },
    { "text": "Eshikni yopib yuring, molni o‘g‘ri olmasin." },
    { "text": "Sizda qancha 'brak' bor? Erkakcha gaplashing." },
    { "text": "Mahsulotni beton ustiga qo‘ymang." },
    { "text": "Tarozi aldamaydi, agar siz aldamasangiz." },
    { "text": "Yuk xati (nakladnoy) qayerda? Yo‘qotmang." },
    { "text": "Eksportga yuk ortyapmizmi?" },
    { "text": "Omborda joy qolmadi, ofisga taxlaymizmi?" },
    { "text": "Revizor kelyapti, tayyor turing." },
    { "text": "Ombor hidi — erkak kishiga yoqadi." },

    { "text": "Pul sanashni yoqtirasiz, bilaman." },
    { "text": "Kassa minusda, yurak sanchyapti." },
    { "text": "Byudjetni tasdiqlash — jangga kirishdek gap." },
    { "text": "Soliqchi kelyapti — kostyum-shimni kiying." },
    { "text": "Foyda qani? Menga natija kerak." },
    { "text": "Xarajatlarni qisqartiramiz, birinchi navbatda kofedan." },
    { "text": "Dollarning kursi oshdi, kayfiyat tushdi." },
    { "text": "Moliyaviy hisobot — bu eng qiziqarli detektiv." },
    { "text": "Pulni havoga sovurmang, bu oson topilmagan." },
    { "text": "Buxgalter bilan hazillashmang, oylikni kechiktiradi." },
    { "text": "Investitsiya kerak, qayerdan topamiz?" },
    { "text": "Qarz daftari 'Voyna i mir' bo‘lib ketdi." },
    { "text": "Dividentlarni qachon olamiz, aka?" },
    { "text": "1 tiyinning ham hisobi bor." },
    { "text": "Inkassatorlar kechikyapti." },
    { "text": "Plastik kartada pul bor, naqd muammo." },
    { "text": "Bank bizni qora ro‘yxatga tiqmasin." },
    { "text": "Moliyaviy direktor hozir asabiy, kirmang." },
    { "text": "Bu narxlar qayerdan keldi? Osmondanmi?" },
    { "text": "Rentabellik past, ishni kuchaytiring." },
    { "text": "Balansni nolga keltirish — bu san'at." },
    { "text": "Pul — qo‘lning kiri, lekin bizga kir kerak." },
    { "text": "Smetadan chiqib ketmang." },
    { "text": "Audit tekshiruvi — bu do‘zaxning kichik filiali." },
    { "text": "Qora kassa haqida gapirmang, devorning qulog‘i bor." },
    { "text": "Biznesda do‘st bo‘lmaydi, faqat hamkor." },
    { "text": "Pullar suvdek oqib kelsin, ilohim." },
    { "text": "Boy bo‘lish ayb emas." },
    { "text": "Soliqlarni to‘lab, tinch uxlang." },
    { "text": "Kredit yopish kerak, bosh qotdi." },

    { "text": "Bugun choyxonaga boramizmi?" },
    { "text": "Oshni yog‘li qiling, parhez xotinlarga." },
    { "text": "Mashinangizni yuvdiring, yomg‘ir yog‘adi." },
    { "text": "Futbolni ko‘rdingizmi? Hakam ko‘r ekan." },
    { "text": "Benzin narxi oshdi, velosiped minamizmi?" },
    { "text": "Xotin 'uyga vaqtli keling' dedi, demak kech boramiz." },
    { "text": "Bugun payshanba — osh kuni." },
    { "text": "Gap (uliat) qachon? Pul yig‘ish kerak." },
    { "text": "Usta mashinani buzib qo‘ydi." },
    { "text": "Soch to‘kilyapti, bu aqldan (yoki asabdan)." },
    { "text": "Qorin qo‘ydingiz, aka, zalga boring." },
    { "text": "Erkak kishi yig‘lamaydi, faqat 'nedostacha' chiqqanda." },
    { "text": "Uyda boss (xo‘jayin) kim? Albatta, men (xotin yo‘g‘ida)." },
    { "text": "Qaynona keldimi? Uyga borishga shoshilmang." },
    { "text": "Bolalar maktabi, bog‘chasi... pul yetkazib bo‘lmaydi." },
    { "text": "Baliq oviga ketsak bo‘lardi, telefonni o‘chirib." },
    { "text": "Shashlik yegim kelyapti, somsa emas." },
    { "text": "Bizning ishimiz — oilani boqish." },
    { "text": "Erkakning so‘zi bitta bo‘ladi (ba’zan ikkita)." },
    { "text": "Do‘stlar bilan o‘tirish — bu psixoterapiya." },
    { "text": "Telefoningizni xotini tekshirmaydimi?" },
    { "text": "Bugun dam olish kuni, lekin biz ishlaymiz." },
    { "text": "Uyqu — bu zaiflar uchun (hazil, uxlash kerak)." },
    { "text": "Biznes-lanchga nima bor? Yana tovuqmi?" },
    { "text": "Qarz so‘ramang, munosabat buziladi." },
    { "text": "Ayollar bizni tushunmaydi." },
    { "text": "Sovg‘a olish kerak, esdan chiqibdi." },
    { "text": "Bugun kayfiyat zo‘r, choy damlang." },
    { "text": "Haqiqiy erkak xamir qormaydi, u tizimni boshqaradi." },

    { "text": "Biz baribir o‘lamiz, shuning uchun ishlayveramiz." },
    { "text": "Do‘zaxda alohida ofis bor... buxgalterlar va direktorlar uchun." },
    { "text": "Sizning o‘rningizga robot keladi, u arzonroq." },
    { "text": "Hayot qiyin, lekin biz O‘zbekistondamiz, uddalaymiz." },
    { "text": "Pechkada kuyishdan yomoni — soliq tekshiruvi." },
    { "text": "Biz qul emasmiz, biz 'shartnoma asosidagi xodimmiz'." },
    { "text": "Maoshni kutish — bu eng katta sabr sinovi." },
    { "text": "Jahannam olovi bizning sexdan salqinroq." },
    { "text": "Stressni ichimlik bilan emas, ish bilan o‘ldiramiz." },
    { "text": "Sizning asablaringiz po‘latdan, lekin zanglayapti." },
    { "text": "Qarilikda nima qilamiz? Ombor mudiri bo‘lamiz." },
    { "text": "O‘lim haq, soliqlar ham haq." },
    { "text": "Tobutni qimmatidan buyurtma qiling, baribir pul topdingiz." },
    { "text": "Biz shunchaki statistikamiz." },
    { "text": "Ishxonada uxlash — bu san'at." },
    { "text": "Boshliq baqiryaptimi? Demak, u tirik." },
    { "text": "Yurakurug‘ingizni ehtiyot qiling, ehtiyot qismlar qimmat." },
    { "text": "Pensiya yoshiga yetib boramizmi?" },
    { "text": "Miya qurib qoldi, suv quying." },
    { "text": "Ko‘zlar qizarib ketdi, vampirga o‘xshab." },
    { "text": "Biz zombimiz, faqat kofe bilan ishlaymiz." },
    { "text": "Dushanba — og‘ir kun, seshanba ham, chorshanba ham..." },
    { "text": "Oylikni xotinga beramiz, o‘zimizga nima qoladi?" },
    { "text": "Erkak bo‘lish qiyin, lekin kimdir bo‘lishi kerak." },
    { "text": "Tizim qulasa, bayram qilamiz." },

    { "text": "Tort yeyish erkakning ishi emas... deymiz-u, yeymiz." },
    { "text": "Somsa bormi? Go‘shtli bo‘lsin." },
    { "text": "Shirinlikni bolalarga olib ketaman." },
    { "text": "Nonni uydagilar kutyapti." },
    { "text": "Buxanka noni eng to‘yimlisi." },
    { "text": "Napoleonni xotinim yaxshi ko‘radi." },
    { "text": "Pechka oldida turmang, erib ketasiz." },
    { "text": "Xamirni ayollar qorsin, biz hisoblaymiz." },
    { "text": "Shakar narxi oshdi, choyni shirin qilmaymiz." },
    { "text": "Un qopini ko‘tarish — trenirovka." },
    { "text": "Qaymoqli tort — xolesterin bombasi." },
    { "text": "Bizning mahsulot — strategik ahamiyatga ega." },
    { "text": "Non bor joyda ochlik yo‘q." },
    { "text": "Mijozlar injiq, xuddi yosh boladek." },
    { "text": "Sifat nazorati — bu bizning burchimiz." },
    { "text": "Kuygan nonni o‘zimiz yeymiz, sotmaymiz." },
    { "text": "Nonvoyxona — bu issiq joy (majoziy ma'noda)." },
    { "text": "Bugun qaysi tortni 'brak' qilamiz (yeyish uchun)?" },
    { "text": "Pechkani gazini o‘chirish esdan chiqmasin." },
    { "text": "Tandir noniga yetmaydi baribir." },
    { "text": "Chet elning kruassani bizning somsaga dam soladi." },
    { "text": "Qora non — haqiqiy erkaklar uchun." },
    { "text": "Och qoringa ishlash — bu jinoyat." },
    { "text": "Tushlikka chiqish uchun ruxsatnoma shart emas." },

    { "text": "Majlisda gapirmang, aqlli ko‘rinasiz." },
    { "text": "Galstuk bo‘g‘ib qo‘ydi." },
    { "text": "Kostyum-shimda yurish noqulay." },
    { "text": "Konditsionerni yoqing, pishib ketdik." },
    { "text": "Ofis planktoni bo‘lmang, harakat qiling." },
    { "text": "Karyera zinapoyasi liftda emas, piyoda chiqiladi." },
    { "text": "Korporativ bayramda ko‘p ichmang." },
    { "text": "Boshliq doim haq, buni unutmang." },
    { "text": "Jamoaviy ruh — bu 'birimiz hamma uchun'." },
    { "text": "Byurokratiya qog‘ozlari to‘yib yubordi." },
    { "text": "Imzo qo‘yishdan oldin o‘qing." },
    { "text": "Pechat (muhr) qayerda? Seyfdami?" },
    { "text": "Kotiba qizga gap otmang, u hamkasb." },
    { "text": "Ish vaqti tugadi, uyga qochamiz." },
    { "text": "Ishxonada ishqiy munosabat taqiqlangan (norasmiy)." },
    { "text": "Stol ustini yig‘ishtiring, tartib bo‘lsin." },
    { "text": "Kreslo qulaymi? Boshliqnikidek emas-ku." },
    { "text": "Muzokaralar og‘ir o‘tdi." },
    { "text": "Shartnoma tuzdik, endi bajarish kerak." },
    { "text": "Raqobatchilar uxlamayapti, biz ham turaylik." },
    { "text": "Biznes reja — bu ertak, lekin ishonish kerak." },
    { "text": "Strategiya yo‘q, faqat 'davay-davay' bor." },
    { "text": "KPI bajarildi, bonus qani?" },
    { "text": "Xodimlar kechikyapti, jarima solamiz." },
    { "text": "Direktor xonasiga chaqiryapti, duo qiling." },

    { "text": "Internetni o‘chirib qo‘yaman, ishlang." },
    { "text": "Sizning parolingiz juda oddiy, o‘zgartiring." },
    { "text": "Kaps Lock yonib qolibdi, baqirmang." },
    { "text": "Sichqoncha simsizmi? Batareyasi tugabdi." },
    { "text": "Ekranni mushtlamang, u aybdor emas." },
    { "text": "Dasturchi ham odam, unga ham qiyin." },
    { "text": "Backup (nusxa) oldingizmi? Keyin kech bo‘ladi." },
    { "text": "Excel jadvallari — bu erkakning 'LEGO'si." },
    { "text": "Alt+Tab ni tez bosishni o‘rganing (boshliq kelganda)." },
    { "text": "Tizim yangilanyapti, kofe ichib turing." },
    { "text": "Sizning faylingiz saqlanmadi... hazil." },
    { "text": "Bulutli texnologiya — bu yomg‘ir yog‘adi degani emas." },
    { "text": "Server xonasi eng salqin joy." },
    { "text": "Printer kartriji qimmat, tejang." },
    { "text": "Qog‘ozni ikki tomonlama ishlating." },
    { "text": "Skaner ishlamayapti, rasmga oling." },
    { "text": "Elektron pochta to‘lib ketdi, tozalang." },
    { "text": "Spamni ochmang, virus tushadi." },
    { "text": "Antivirus baqiryapti, nimalarni ko‘chirgansiz?" },
    { "text": "Google hamma narsani biladi, mendan so‘ramang." },
    { "text": "Bu tugma 'Delete', ehtiyot bo‘ling." },
    { "text": "Shift tugmasi yopishib qoldi." },
    { "text": "Klaviatura ostida non ushog‘i bormi?" },
    { "text": "Siz IT mutaxassisi emassiz, buzmang." },
    { "text": "Restart — 90% muammoni hal qiladi." },

    { "text": "Aka, bu ishni bitiraylik, keyin gaplashamiz." },
    { "text": "Erkakcha va’da bering." },
    { "text": "Lafz bormi? Bajaring." },
    { "text": "Mard bo‘ling." },
    { "text": "G‘iybat qilmang, ayollarga xos." },
    { "text": "Ishni halol qiling." },
    { "text": "Qo‘lni bering, kelishdik." },
    { "text": "Hurmat qiling, hurmat ko‘rasiz." },
    { "text": "Kattalarni hurmat qiling." },
    { "text": "Ukajon, choy damlang." },
    { "text": "Aka, yo‘l-yo‘riq ko‘rsating." },
    { "text": "Tajriba — eng yaxshi ustoz." },
    { "text": "Xatolardan qo‘rqmang, tuzatamiz." },
    { "text": "Boshni baland ko‘taring." },
    { "text": "Belni mahkam bog‘lang." },
    { "text": "Oila muqaddas." },
    { "text": "Vatan uchun, oila uchun ishlaymiz." },
    { "text": "Bizning jamoa — eng zo‘ri." },
    { "text": "Raqobat — bu yaxshi." },
    { "text": "Muvaffaqiyat kaliti — mehnat." },
    { "text": "Oson pul bo‘lmaydi." },
    { "text": "Ter to‘kib topilgan non shirin." },
    { "text": "Haramdan uzoq bo‘ling." },
    { "text": "Insof sari baraka." },
    { "text": "Sizga ishonaman." },

    { "text": "Bugun chempionlar ligasi, uxlash yo‘q." },
    { "text": "Real yoki Barsa? Tizim neytral." },
    { "text": "Mashinaga gaz qo‘ydirdingizmi?" },
    { "text": "Propanda navbat katta ekan." },
    { "text": "Tonerovka ruxsatnomasi bormi?" },
    { "text": "Radar tushdi, jarima to‘lash kerak." },
    { "text": "GAI to‘xtatdi, kayfiyat yo‘q." },
    { "text": "Mashina yuvishga vaqt yo‘q." },
    { "text": "Balon teshildi, zapaska bormi?" },
    { "text": "Akumulyator o‘tirdi." },
    { "text": "Svetofor ishlamayapti, probka." },
    { "text": "Taksistlar gapdon bo‘lib ketgan." },
    { "text": "Avtokredit yopilmayapti." },
    { "text": "GM mashinasi — milliy boylik (hazil)." },
    { "text": "Mersedes olish orzusi." },
    { "text": "Baliq ovi mavsumi ochildimi?" },
    { "text": "Ovga chiqamizmi?" },
    { "text": "Tog‘ga borib dam olaylik." },
    { "text": "Shashlik pishirish san'at." },
    { "text": "Karta o‘ynash ofisda taqiqlangan." },
    { "text": "Narda tashlaymizmi?" },
    { "text": "Bilyardga boramiz ishdan keyin." },
    { "text": "Hovlida ish ko‘p." },
    { "text": "Tomni yopish kerak." },
    { "text": "Usta topish muammo." },
    { "text": "Sement narxi oshdi." },
    { "text": "Uy qurish — azob, lekin zavqli." },
    { "text": "O‘g‘il uylantirish kerak." },
    { "text": "Qiz chiqarish kerak." },
    { "text": "To‘y qilish oson emas." },

    { "text": "Qani, ishga kirishaylik, Bismillah." },
    { "text": "Bugungi ishni ertaga qo‘ymang." },
    { "text": "Harakatda — baraka." },
    { "text": "Dangasalik — dushman." },
    { "text": "Vaqt — g‘animat." },
    { "text": "Siz professionalsiz, shunga mos bo‘ling." },
    { "text": "Boshqalar gapiradi, biz qilamiz." },
    { "text": "Natija muhim." },
    { "text": "Bahona qilmang." },
    { "text": "Yechim toping, muammo emas." },
    { "text": "Miya ishlasin." },
    { "text": "Qo‘l ishlasin." },
    { "text": "Ko‘z ko‘rsin." },
    { "text": "Quloq eshitsin." },
    { "text": "Tizim sizga yordamchi." },
    { "text": "Biz texnologiya asridamiz." },
    { "text": "Qog‘ozbozlikni yo‘qotamiz." },
    { "text": "Raqamli iqtisodiyotga o‘tamiz." },
    { "text": "ERP — bu kelajak." },
    { "text": "Siz tizimni boshqaring, u sizni emas." },
    { "text": "Logotipga bosganda tabassum qiling." },
    { "text": "Ishingizdan faxrlaning." },
    { "text": "Nonvoylik — sharaf." },
    { "text": "Oziq-ovqat xavfsizligi sizning qo‘lingizda." },
    { "text": "Xalqni boqayapsiz, rahmat." }
]

export const mobileQuotes = [
    { "text": "Tirnoq bilan bosmang, ekran qimmat turadi." },
    { "text": "Yana Instagram'mi? Ishga qarang, go‘zalim." },
    { "text": "Bu tugmani bosish uchun ingichka barmoqlar kerak." },
    { "text": "Telefoningiz qizib ketdi, xuddi asabingizdek." },
    { "text": "Batareyangiz ham sizga o‘xshab 'o‘lay' deyapti-ku." },
    { "text": "Smenani tekshiryapsizmi yoki o‘zingizni ko‘zguda ko‘ryapsizmi?" },
    { "text": "Barmoq izi ishlamayapti, qo‘llar xamir bo‘libdi." },
    { "text": "Ekranni kattalashtirmang, smena qisqarib qolmaydi." },
    { "text": "Telefonni yuzga yaqin tutmang, nuridan ajin tushadi." },
    { "text": "Svayp qilmang, bu Tinder emas, bu ish jadvali." },
    { "text": "Sizning telefoningiz bizning pechkamizdan ham ko‘p ishlaydi." },
    { "text": "Ekranni tonal krem qilib yuboribsiz, arting." },
    { "text": "Wi-Fi qidirguncha, mijozga qarang." },
    { "text": "Selfi tushishga vaqt yo‘q, tort erib ketdi." },
    { "text": "Smenani skrinshot qilib oling, yana 'esimdan chiqibdi' demang." },
    { "text": "Telefoningiz xotirasi to‘ldi, bizning ombor ham." },
    { "text": "Bu ilova sizning 'filtr'laringizdan ham chiroyli." },
    { "text": "Scroll qilishdan barmoqlar ozib ketdi." },
    { "text": "Telegramdagi g‘iybat qochib ketmaydi." },
    { "text": "Siz telefonga termulib, kruassanlar kuyib ketmasin." },
    { "text": "Bu tugma 'Layk' tugmasi emas, bu 'Tasdiqlash'." },
    { "text": "Internet sekinmi yoki siz uxlayapsizmi?" },
    { "text": "Blokirovka qilib qo‘ying, boshliq ko‘rmasin." },
    { "text": "Zaryadnik bormi? Hamma shu dardda." },
    { "text": "Telefonni sumkaga soling, hayotga qayting." },
    { "text": "Yana bitta bildirishnoma kelsa, telefon portlaydi." },
    { "text": "Sizning manikyuringizga gap yo‘q, lekin tugmani sekinroq bosing." },
    { "text": "FaceID sizni tanimayapti, makiyajsiz kelibsiz-da." },
    { "text": "Telefonda smenani ko‘rib, kayfiyatingiz tushmasin." },
    { "text": "Mijozlar kutib qoldi, telefonni o‘chiring." },
    { "text": "Siz onlaynsiz, lekin ishda oflaynsiz." },
    { "text": "Bu funksiya 'Istoriya' ko‘rish uchun emas." },
    { "text": "Ekranni teshib qo‘yaman dedingizmi?" },
    { "text": "Klik qilaverib manikyurni buzib qo‘ymang." },
    { "text": "Telefoningiz juda aqlli, siz-chi?" },
    { "text": "Quvvatlash foizi 1%, xuddi sabrim kabi." },
    { "text": "Guruhdagi yozishmalarni o‘qimang, asab buziladi." },
    { "text": "Silent rejimga qo‘ying, eringiz tinmayapti." },
    { "text": "Musiqani o‘chiring, bu yer diskoteka emas." },
    { "text": "Kamerani yoping, sizni kuzatishmoqda (hazil)." },
    { "text": "Bu ilova faqat go‘zallar uchun ishlaydi." },
    { "text": "Sizning telefoningiz — sizning eng yaqin dugonangiz." },
    { "text": "Aloqa yo‘q, demak ishlash kerak." },
    { "text": "Mobil internetingiz tugayapti, tejang." },
    { "text": "Ekranni sindirmang, ustaga berishga pul yo‘q." },
    { "text": "Tugmani bosishga erinyapsizmi? Ha, malikasiz-da." },
    { "text": "Jadvalni kattalashtirib ko‘ring, balki dam olish kuni bordir." },
    { "text": "Telefoningiz sizdan ko‘p narsani biladi." },
    { "text": "Parolni esingizdan chiqardingizmi? Xuddi tug‘ilgan kunlarni unutgandek." },
    { "text": "Restart bering, o‘zingizga ham." },

    { "text": "Salom, {name}. Qoshlaringiz bugun o‘xshabdi!" },
    { "text": "{name}, yana sizmi? Biz sizsiz zerikkan edik." },
    { "text": "{name}, bugun smenada kim bilan ekaningizni ko‘rdingizmi? Sabr..." },
    { "text": "{name}, telefonni qo‘ying, mijoz sizga oshiq bo‘lib qoldi." },
    { "text": "{name}, bugun parhezni buzamizmi?" },
    { "text": "{name}, sizni 'Yil xodimi' qilamiz... agar telefonni qo‘ysangiz." },
    { "text": "{name}, bugun juda ochilib ketibsiz, ko‘z tegmasin." },
    { "text": "{name}, smena tugashiga hali erta, soatga qaramang." },
    { "text": "{name}, eringiz qo‘ng‘iroq qilyapti: 'Ovqat qani?' deb." },
    { "text": "{name}, sochingizni kim turmakladi? Zo‘r!" },
    { "text": "{name}, bugun ishdan keyin qayerga? To‘g‘ri uyga!" },
    { "text": "{name}, bu ko‘ylagingizni qayerdan oldingiz?" },
    { "text": "{name}, sizsiz bu smena — xuddi shakarsiz choydek." },
    { "text": "{name}, asabiylashmang, yuzingizga ajin tushadi." },
    { "text": "{name}, bu smenada uxlab qolmang." },
    { "text": "{name}, siz malikasiz, lekin hozircha fartuk taqqan malika." },
    { "text": "{name}, dugonangiz bilan g‘iybatni keyinga qoldiring." },
    { "text": "{name}, bugun kimnidir xursand qiling (masalan, meni)." },
    { "text": "{name}, oynaga kamroq qarang, shundoq ham go‘zalsiz." },
    { "text": "{name}, smenani almashtirish yo‘q, bahona qilmang." },
    { "text": "{name}, 'Medovik' yegingiz kelyapti, sezib turibman." },
    { "text": "{name}, bugun kayfiyatingiz 'O‘zbekfilm'mi yoki 'Gollivud'?" },
    { "text": "{name}, siz bu kompaniyaning bezagisiz." },
    { "text": "{name}, ish jadvali o‘zgarmas, xuddi qaynona kabi." },
    { "text": "{name}, o‘zingizni ehtiyot qiling, siz bizga keraksiz." },
    { "text": "{name}, yana kech qoldingizmi? 'Probka' deng." },
    { "text": "{name}, hisobotni topshiring, keyin choy ichamiz." },
    { "text": "{name}, siz kuchlisiz, hammasiga ulgurasiz." },
    { "text": "{name}, qorningiz ochdimi? Menga ham." },
    { "text": "{name}, bugun tabassumingiz bilan hammani yiqitasiz." },
    { "text": "{name}, Bormi og'riq?" },

    { "text": "Parhez — dushanba kuni boshlanib, seshanbada tugaydigan narsa." },
    { "text": "Agar shokolad sabzavot bo‘lganda edi, dunyo go‘zal bo‘lardi." },
    { "text": "Tarozi buzilgan, u har doim noto‘g‘ri ko‘rsatadi." },
    { "text": "Ozg‘inlik modadan qoldi, endi 'shirin' bo‘lish moda." },
    { "text": "Kruassanlar belga yig‘iladi, lekin ular shunga arziydi." },
    { "text": "Asabim buzildi... demak, ekler yeyish kerak." },
    { "text": "Biz kaloriyalarni sanamaymiz, biz ularni yeymiz." },
    { "text": "Sport zaliga pul to‘ladim, lekin borishga vaqt yo‘q (bahona)." },
    { "text": "Stressni yeyish bilan davolaymiz." },
    { "text": "Kechki 6 dan keyin yemaslik — bu afsona." },
    { "text": "Non hidi — bu eng katta fitna, chidab bo‘lmaydi." },
    { "text": "Bir bo‘lak tortdan hech kim semirib ketmagan (dedi shayton)." },
    { "text": "Qomatni saqlash qiyin, ishni saqlash undanam qiyin." },
    { "text": "Oyna aytadi: 'Ye', tarozi aytadi: 'To‘xta'." },
    { "text": "90-60-90 bo‘lish shart emas, asosiysi qosh chizilgan bo‘lsin." },
    { "text": "Erkaklar qorin bilan sevadi, biz esa tort bilan." },
    { "text": "Pechka issig‘ida yog‘lar eriydi deb o‘ylagan edim... yanglishibman." },
    { "text": "Muzlatgich — mening eng yaqin sirdoshim." },
    { "text": "Ozish uchun asabni tinchlantirish kerak (tort bilan)." },
    { "text": "Yozga ozish rejasi barbod bo‘ldi, endi Yangi yilga." },
    { "text": "Shirinliksiz hayot — xuddi bo‘yoqsiz yuzdek rangsiz." },
    { "text": "Men shirinlikni sevaman, u ham meni sevadi, bu o‘zaro muhabbat." },
    { "text": "Qizlar, bugun bayram qilamiz, parhez bekor." },
    { "text": "Qomat — o‘tkinchi, ishtaha — abadiy." },
    { "text": "Mening qornim to‘q, lekin ko‘zim och." },
    { "text": "Bugun 'Napaleon' yeymiz, belimiz ko‘rmasin." },
    { "text": "Siz shunchalik shirinsizki, qandli diabet bo‘lishim mumkin." },
    { "text": "Tortni ko‘rganda, parhez 'hushidan ketdi'." },
    { "text": "Yana bitta bulochka? Mayli, buguncha mumkin." },
    { "text": "Shokolad baxt gormoni, biz esa baxt ulashamiz." },

    { "text": "Biz baribir qariymiz, shuning uchun tort yeylik." },
    { "text": "Jannatda tort bormikan? Bo‘lmasa bormayman." },
    { "text": "Hayot qisqa, ayniqsa dam olish kunlari." },
    { "text": "Bizning pechka do‘zaxdan issiqroq." },
    { "text": "Asab hujayralari tiklanmaydi, mijozlar buni bilmaydi." },
    { "text": "O‘lsak ham smenada o‘lamiz shekilli." },
    { "text": "Kuygan non — mening hayotim ramzi." },
    { "text": "Zombi apokalipsis bo‘lsa, bizda non bor, yashab qolamiz." },
    { "text": "Pardoz qilmasangiz, mijozlar qo‘rqib ketadi." },
    { "text": "Erga tegmaganlar, shoshilmang, u yoqda ham ish ko‘p." },
    { "text": "Bolalar yig‘laydi, er so‘raydi, ish kutadi... Men robotman." },
    { "text": "Mening tobutimni 'Napaleon' shaklida qilinglar." },
    { "text": "Qarilik — bu smenadan keyin bel og‘rishi." },
    { "text": "Yuragim yo‘q, o‘rnida keks bor." },
    { "text": "Mijozni o‘ldirib qo‘ymaslik uchun chuqur nafas oling." },
    { "text": "Biz zaharni shakar bilan o‘rab sotamiz (hazil)." },
    { "text": "Sizning joningiz kompaniyaga tegishli." },
    { "text": "Uyqu — bu kichik o‘lim, biz esa tirikmiz." },
    { "text": "Mening ko‘z yoshlarim xamirga tuz bo‘lib qo‘shiladi." },
    { "text": "Ajinlar ko‘payyapti, oylik esa..." },
    { "text": "Meni pechkaga solib yuboring, isisin." },
    { "text": "Miya faoliyati to‘xtadi, faqat qo‘llar ishlayapti." },
    { "text": "Ertaga uyg‘onmasam, smenaga kim chiqadi?" },
    { "text": "Hayot — bu azob, tort esa vaqtinchalik 'og‘riqsizlantiruvchi'." },
    { "text": "Sizni almashtirish oson, lekin sog‘inishadi." },
    { "text": "Dunyoni go‘zallik qutqaradi... biz esa charchadik." },
    { "text": "Mening ruhiy holatim: 'Uvalangan pechenye'." },
    { "text": "Do‘zaxda alohida qozon bor... injiq mijozlar uchun." },
    { "text": "O‘lim va soliqlar — qochib bo‘lmas narsalar." },
    { "text": "Yoshlik qaytmaydi, lekin ortiqcha vazn qaytadi." },

    { "text": "Ertalab turish — bu kunning eng og‘ir sinovi." },
    { "text": "Smena tugashiga 5 daqiqa qoldi... eng uzoq 5 daqiqa." },
    { "text": "Bugun kim bilan ishlayman? Ilohim, chaqqonrog‘i bo‘lsin." },
    { "text": "Dam olish kuni faqat tushingizda kiradi shekilli." },
    { "text": "Oyoqlarim uzilib tushdi, yangi oyoq bormi?" },
    { "text": "Smenadan keyin uyga emas, reanimatsiyaga ketgim kelyapti." },
    { "text": "Yakshanba kuni ishlash — bu qahramonlik." },
    { "text": "Grafikga qarab xo‘rsinmang, yuzingizga yarashmaydi." },
    { "text": "Tungi smena — yalmog‘izga aylanish vaqti." },
    { "text": "Dugonangiz kasal bo‘ldimi? Demak, siz ikki hissa ish." },
    { "text": "Ish vaqti tugadi, lekin mijozlar tugamadi." },
    { "text": "Smena jadvalini ko‘rib, 'Maldiv' orollari esimga tushib ketdi." },
    { "text": "Erta tongda avtobusda uxlash — bu alohida san'at." },
    { "text": "Uyga borganingizda oyog‘ingizni ko‘tarib yoting." },
    { "text": "Sizning smenangiz — bu pekarxonaning yuragi uradigan vaqt." },
    { "text": "Jadvalni buzmang, karma bor." },
    { "text": "Bugun ishga kelmay qo‘ysammikan? Yo‘q, tort yegim kelyapti." },
    { "text": "Ishxonadagi g‘iybat — smenaning eng shirin qismi." },
    { "text": "Meni uyg‘otmang, men hali smenadaman." },
    { "text": "Tushlikka chiqish — muqaddas vaqt, bezovta qilinmasin." },
    { "text": "Smena tugadimi? Yo‘q, hali tozalash kerak." },
    { "text": "Bugun mijozlar ko‘p, poshnali tufli kiymang." },
    { "text": "Soat millari muzlab qolganmi?" },
    { "text": "Jadvalda bo‘sh joy yo‘q, xuddi avtobus kabi." },
    { "text": "Hafta oxiri — bu shunchaki kalendardagi so‘z." },
    { "text": "Bayramlarda ishlashni yaxshi ko‘ramiz (majburan)." },
    { "text": "Smenadan keyin meni ko‘taringlar." },
    { "text": "Ko‘zlarim ochiq, lekin miyam uxlab yotibdi." },
    { "text": "Bu smena qachondir tugaydimi?" },
    { "text": "Ish — bo‘ri emas, o‘rmonga qochmaydi... afsuski." },

    { "text": "Kruassanlar to‘g‘ri chiqmayapti, kayfiyati yo‘q shekilli." },
    { "text": "Tortni kim kesdi? Bo‘lagi juda katta-ku." },
    { "text": "Pechenye qattiq bo‘lsa, choyga botirib yeymiz." },
    { "text": "Napoleon qavatlari mening ajinlarimdan kam." },
    { "text": "Ekler ichida krem yo‘q, lekin muhabbat bor." },
    { "text": "Non isi — eng zo‘r atir, 'Chanel'dan yaxshi." },
    { "text": "Medovik juda shirin, xuddi siz kabi." },
    { "text": "Xamir oshib ketdi, bizning orzular kabi." },
    { "text": "Mijozga kuygan non bermang, uyat bo‘ladi." },
    { "text": "Tort ustidagi gilosni men yeyman!" },
    { "text": "Pirojkilar sovib qoldi, mikroto‘lqinli pech qani?" },
    { "text": "Keks quruq bo‘lib qoldi, sharbat bilan bering." },
    { "text": "Bu 'Napoleon' emas, bu shunchaki san'at." },
    { "text": "Pechenye kuyib ketdi, 'negr' pechenye deb sotamiz." },
    { "text": "Shakar tugadi, hayotimiz shundoq ham shirin." },
    { "text": "Un hidi 'Gucci' atiridan ham yoqimliroq." },
    { "text": "Quruq mevalarni kim terib yedi?" },
    { "text": "Vanilin qayerda? Hamma yoq xushbo‘y bo‘lib ketibdi." },
    { "text": "Sgushonka bankasini ochish — bu bayram." },
    { "text": "Mayizlarni non ichidan qidirib toping." },
    { "text": "Mahsulotlarni isrof qilmang, uvol bo‘ladi." },
    { "text": "Xamir qorish — qo‘llar uchun eng yaxshi mashq." },
    { "text": "Pechka oldida turish — bu bepul sauna." },
    { "text": "Krem surtish — rassomlik qobiliyatini talab qiladi." },
    { "text": "Tortni bezash — yuzni bo‘yashdek nozik ish." },
    { "text": "Meringa (beze) — bu shunchaki shirin havo." },
    { "text": "Ruletni o‘rash — hayotni izga solishdek qiyin." },
    { "text": "Shokoladni eritish — sabr maktabi." },
    { "text": "Pirojiniy — kichkina baxt bo‘lagi." },
    { "text": "Somsa — bu milliy fast-fud, baribir mazali." },

    { "text": "Mijoz har doim haq, garchi didi bo‘lmasa ham." },
    { "text": "Boshliq bugun yaxshi kayfiyatda, foydalanib qoling." },
    { "text": "Biz bir oilamiz, faqat janjalkashroq." },
    { "text": "Ishxonadagi g‘iybat — eng issiq yangiliklar." },
    { "text": "Dugonalar, tezroq ishlaylik, serial boshlanadi." },
    { "text": "Bizda pekarxona, go‘zallik saloni emas (lek biz go‘zalmiz)." },
    { "text": "Korporativ madaniyat — bir-birimizni asraymiz." },
    { "text": "Mijoz 'shirinlik bering' desa, o‘zingizni ko‘rsatmang." },
    { "text": "Direktor xonasiga kirishdan oldin oynaga qarang." },
    { "text": "Tabassum — bizning eng kuchli qurolimiz." },
    { "text": "Ishdagi muammolar ishda qolsin." },
    { "text": "Bugun kim kofe damlaydi? Men emas." },
    { "text": "Ayol kishi hamma narsaga ulguradi: ishga ham, uyga ham." },
    { "text": "Erkaklar tushunmaydi bizning ishni." },
    { "text": "Bizning jamoa — 'G‘iybat va Shirinliklar' klubi." },
    { "text": "Siz kuchlisiz, hammasini uddalaysiz." },
    { "text": "Ayol kishi ojiza emas, u mo‘jiza." },
    { "text": "Bugun o‘zingizga vaqt ajrating." },
    { "text": "Siz bu kompaniyaning yuragisiz." },
    { "text": "Mijozlarga jilmaying, ular ham shirinlik istaydi." },
    { "text": "Nonvoy qizlar — eng sabrli qizlar." },
    { "text": "Boshliq kelyapti, ishlayotgandek turing." },
    { "text": "Kassir qiz, jilmayib turing, pul kelyapti." },
    { "text": "Omborchi qiz, bugun jiddiy." },
    { "text": "Xavfsizlik texnikasi — sochni yig‘ib yuring." },
    { "text": "Korporativ qul bo‘lmang, malika bo‘ling." },
    { "text": "Miting vaqti — g‘iybat vaqti emas." },
    { "text": "Shikoyat kitobi to‘ldi, yangisini oching." },
    { "text": "Rahmat deng, tilingizdan bol tomadi." },
    { "text": "Xushmuomala bo‘ling, siz malikasiz." },

    { "text": "Qizlar, charchamang, oz qoldi." },
    { "text": "Dunyoni go‘zallik va shirinlik qutqaradi." },
    { "text": "Sizning qo‘lingiz gul." },
    { "text": "Oynaga qarang, ko‘zingiz yonib turibdi." },
    { "text": "Har bir kuningiz bayram bo‘lsin." },
    { "text": "Sizni yaxshi ko‘ramiz (va tortlaringizni ham)." },
    { "text": "Baxtli ayol — eng chiroyli ayol." },
    { "text": "Ish o‘z yo‘liga, sog‘lik muhimroq." },
    { "text": "Bugun kimnidir xursand qiling." },
    { "text": "O‘zingizni seving, siz yagonasiz." },
    { "text": "Shopping — bu eng yaxshi terapiya." },
    { "text": "Yangi ko‘ylak sotib olishni unutmang." },
    { "text": "Sizning energiyangiz butun ofisni yoritmoqda." },
    { "text": "Siz robotsiz emas, malikasiz. Sekinroq ishlang." },
    { "text": "Tinchlaning va choy iching." },
    { "text": "Nafas oling, nafas chiqaring... va yana ishlang." },
    { "text": "Asabni asrang, u tiklanmaydi, dugona." },
    { "text": "Sizga ta'til kerak, Maldiv orollarida." },
    { "text": "Erkaklar pul topadi, biz esa go‘zallik yaratamiz." },
    { "text": "Biznes ledilar, hammasi nazorat ostidami?" },
    { "text": "Kredit karta — zamonaviy ayolning qilichi." },
    { "text": "Pulni seving, u ham sizni sevadi." },
    { "text": "Xarajatlar ko‘p, lekin o‘zimizga achinmaymiz." },
    { "text": "Boy bo‘lish oson, shunchaki ko‘p tort sotish kerak." },
    { "text": "Sizning tabassumingiz serverni ham ishlatib yuboradi." },
    { "text": "Qo‘lingiz darmon ko‘rmasin." },
    { "text": "Logotip sizga salom yo‘llayapti." },
    { "text": "Sizning sabringizga qoyil." },
    { "text": "Barmoqlar mashq qilyaptimi? Yoga bormi?" },
    { "text": "Sichqoncha: 'Meni qo‘yvor, dugona' dedi." },

    { "text": "Un ichidan syurpriz chiqmasin." },
    { "text": "Yog‘ bochkalari oqyapti, moyli bo‘lib ketmang." },
    { "text": "Qoplar yirtiq, ehtiyot bo‘ling." },
    { "text": "Muddati o‘tgan narsa yo‘qmi? Yuzga surtishga yaramaydi." },
    { "text": "Tovarni o‘g‘irlamang, baraka qochadi." },
    { "text": "Qoldiqni kamaytiring, joy ochilsin." },
    { "text": "Mahsulotni yerga qo‘ymang, gunoh." },
    { "text": "Ombor juda sovuq, issiqroq kiyining." },
    { "text": "Hisob-kitobda adashmang, qizlar." },
    { "text": "Tarozi to‘g‘ri ishlayaptimi? O‘zingiz chiqib ko‘ring." },
    { "text": "Yuk mashinasi kelmadi, haydovchi yo‘lda choy ichyapti shekilli." },
    { "text": "Ombor kaliti kimda? Yana sumkada qolib ketdimi?" },
    { "text": "Mahsulotlarni rangi bo‘yicha tartiblang (hazil)." },
    { "text": "Bu qutida nima bor? Sirli sandiq." },
    { "text": "Yaroqlilik muddati tugayapti, tezroq ishlating." },
    { "text": "Omborda joy qolmadi, xuddi shkafimiz kabi." },
    { "text": "Hamma narsa chang bosdi, tozalik kuni e'lon qilamiz." },
    { "text": "Qayta sanang, hisobda xato bor." },
    { "text": "Ombor hidi — mehnat hidi." },
    { "text": "Yuklovchilar charchadi, ularga choy bering." },
    { "text": "Qog‘ozda bor, omborda yo‘q — bu qanday sehr?" },
    { "text": "Sgushonka bankasi bo‘sh, kim yaladi?" },
    { "text": "Tuxumlar sinib qoldi, omlet qilamizmi?" },
    { "text": "Margarin yetmayapti, do‘konga yuguring." },
    { "text": "Vanilin hidi ufurib turibdi." },
    { "text": "Kunjut to‘kilib ketdi, terib oling chumolidek." },
    { "text": "Zemalaklar qayerda qoldi?" },
    { "text": "Ishxonadagi g‘iybat — eng issiq yangiliklar." },
    { "text": "KPI bajarilmasa ham, biz eng zo‘rimiz." },
    { "text": "Jamoaviy ruh — biz bir oilamiz (baqiroq oila)." },
    { "text": "Boshliq hozir qarayapti, ishlayotgandek ko‘rining, go‘zallar." },
    { "text": "Bizda pekarxona, go‘zallik saloni emas." },
    { "text": "Korporativ madaniyat — bir-birimizni asraymiz." },
    { "text": "Yillik hisobot yaqinlashmoqda, valeryanka tayyorlang." },
    { "text": "Bonusni tushingizda ko‘rasiz... hazil, beramiz." },
    { "text": "Ish vaqti tugadi, lekin mijozlar tugamadi." },
    { "text": "Mijoz har doim haq, lekin asabni egovlaydi." },
    { "text": "Bu masalani tezroq hal qiling, sovchilar kelyapti." },
    { "text": "Direktor xonasiga kirishdan oldin oynaga qarang." },
    { "text": "Tushlikka chiqish — muqaddas vaqt." },
    { "text": "Karyera zinapoyasi baland poshnali tuflida qiyin." },
    { "text": "HR sizni kuzatyapti, yaxshi qiz bo‘ling." },
    { "text": "Majlisda uxlamang, tushingizda gapirasiz." },
    { "text": "Sizga bonus yozilmadi, chunki ko‘p gapirdingiz." },
    { "text": "Ishdan keyin qolasiz — bu eng yomon gap." },
    { "text": "Bayramda ham ishlaymiz, xalq xizmatidamiz." },
    { "text": "Boshliqning kayfiyati yo‘q, unga qahva olib boring." },
    { "text": "Hisobotni qayta yozing, chiroyli harflar bilan." },
    { "text": "Ofisdagi kofe tugadi, hayot to‘xtadi." },
    { "text": "Sizga ishonchimiz baland, dugonajon." },
    { "text": "Bugun auditor keladi, eng chiroyli formani kiying." },
    { "text": "Ish stulingizni yig‘ishtiring, sovchilar kelib qolar." },
    { "text": "Xavfsizlik texnikasi — sochni yig‘ib yuring." },
    { "text": "Korporativ qul bo‘lmang, malika bo‘ling." },
    { "text": "Miting vaqti — g‘iybat vaqti emas." },
    { "text": "Tushlikka chiqish taqiqlangan... desam ishonmang." },
    { "text": "Tushuntirish xati yozing: 'Nega bunchalar go‘zalman?'" },
    { "text": "Sizga hayfsan emas, mukofot kerak." },
    { "text": "Bugun shanbalik, tozalik — imondan." },
    { "text": "Mijozga kuygan non bermang." },
    { "text": "Tort ustidagi gilos — bu sizning maoshingiz." },
    { "text": "Pirojkilar sovib qoldi." },
    { "text": "Shokolad kayfiyatni ko‘taradi, hisobot esa tushiradi." },
    { "text": "Keks quruq bo‘lib qoldi, uzr." },
    { "text": "Bu 'Napoleon' emas, bu shunchaki qatlama." },
    { "text": "Napoleon qatlari kamayib qoldi." },
    { "text": "Un qopini kim yirtdi?" },
    { "text": "Pechenye kuyib ketdi, qorayib ketdi." },
    { "text": "Shakar tugadi, choy achchiq." },
    { "text": "Non qattiq, tish sinadi." },
    { "text": "Droja ko‘p qo‘shilibdi, portlaydi." },
    { "text": "Bulochka xom pishibdi." },
    { "text": "Bu non emas, g‘isht." },
    { "text": "Pechka tutab ketdi." },
    { "text": "Xamir oshmayapti." },
    { "text": "Mijozlar nolib ketdi." },
    { "text": "Qaymoq aynib qolmasin." },
    { "text": "Yong‘oqlar qurtlaganmi?" },
    { "text": "Shokolad erib ketdi." },
    { "text": "Somsa go‘shti qani?" },
    { "text": "Pirojki yog‘li bo‘lib ketdi." },
    { "text": "Bu tort emas, san'at asari." },
    { "text": "Nonni issiq yoping." },
    { "text": "Qoliplar yuvilmagan." },
    { "text": "Xamirni yaxshi qoring." },
    { "text": "Pechka harorati baland." },
    { "text": "Sovutgich ishlamayapti." },
    { "text": "Non bor joyda hayot bor." },
    { "text": "Xamirturushdek ko‘payamiz." },
    { "text": "Non qadri — tilla." },
    { "text": "Uvol qilmang, gunoh." },
    { "text": "Nonni teskari qo‘ymang." },
    { "text": "Non ushog‘ini tering." },
    { "text": "Nonvoyning qo‘li gul." },
    { "text": "Issiq non — jon rohati." },
    { "text": "Tandirdan uzilgan non." },
    { "text": "Yopgan noningiz shirin bo‘lsin." },
    { "text": "Non — risq-ro‘zimiz." },
    { "text": "Nonni e'zozlang." },
    { "text": "Non bor uyda fayz bor." },
    { "text": "Qora non ham non." },
    { "text": "Nonni isrof qilmang." },
    { "text": "Siz nonni sevasizmi?" },
    { "text": "Biz non pishiramiz, siz yeyasiz." },
    { "text": "Nonvoyxona — ikkinchi uyimiz." },
    { "text": "Un hidi — eng zo‘r atir." },
    { "text": "Pechka issig‘i — quyosh." },
    { "text": "Nonvoyning yuzi yorug‘." },
    { "text": "Tortni kesishni bilasizmi?" },
    { "text": "Krem ko‘p bo‘lsin." },
    { "text": "Biskvit quruq bo‘lmasin." },
    { "text": "Merenaga o‘xshamay qoldi." },
    { "text": "Glazur yaltiramayapti." },
    { "text": "Mastika qotib qoldi." },
    { "text": "Jem oqib ketdi." },
    { "text": "Kakao yetmayapti." },
    { "text": "Razrixlitel soling." },
    { "text": "Soda ta'mi kelyapti." },
    { "text": "Tuzni unutmang." },
    { "text": "Shakar upasi seping." },
    { "text": "Karamel kuyib ketdi." },
    { "text": "Jele qotmadi." },
    { "text": "Muzqaymoq erib ketdi." },
    { "text": "Vafli yumshab qoldi." },
    { "text": "Pryanika qattiq." },
    { "text": "Chak-chak yopishib qoldi." },
    { "text": "Holva yog‘li." },
    { "text": "Paxlava zo‘r." },
    { "text": "Maffin kichkina." },
    { "text": "Kruassan fransuzcha emas." },
    { "text": "Baget uzun." },
    { "text": "Lavash yirtildi." },
    { "text": "Patir chiroyli." },
    { "text": "Obi non issiq." },
    { "text": "Shirmon non shirin." },
    { "text": "Gijduvon noni mashhur." },
    { "text": "Samarqand noni qattiq." },
    { "text": "Buxoro noni yumshoq." },
    { "text": "Xorazm noni katta." },
    { "text": "Toshkent noni chiroyli." },
    { "text": "Nonushtaga nima bor?" },
    { "text": "Choy bilan keting." },
    { "text": "Mehmon kutyapmiz." },
    { "text": "Dasturxon bezang." },
    { "text": "Shirinlik jon-u dilim." },
    { "text": "Parhezni buzing." },
    { "text": "Bugun bayram." },
    { "text": "Tug‘ilgan kunga tort." },
    { "text": "To‘yga non." },
    { "text": "Fatiha to‘yga patir." },
    { "text": "Hayitga pishiriq." },
    { "text": "Navro‘zga sumalak." },
    { "text": "Pishiriq pishirish san'at." },
    { "text": "Reseptni buzmang." },
    { "text": "Grammlab o‘lchang." },
    { "text": "Ko‘z bilan chamalamang." },
    { "text": "Tarozi aldamaydi." },
    { "text": "Sifat nazorati." },
    { "text": "Ta'mini totib ko‘ring." },
    { "text": "Mijoz rozi bo‘lsin." },
    { "text": "Logotipni bosish oylikni oshirmaydi." },
    { "text": "Yana bosdingizmi? Sichqonchani asrang." },
    { "text": "Bu tugma emas, bu shunchaki bezak." },
    { "text": "Bosish tekin, lekin asablar pullik." },
    { "text": "Logotip qochib ketmaydi, xavotir olmang." },
    { "text": "Siz bosasiz, biz ishlaymiz... adolatsizlik." },
    { "text": "Ekranni teshib qo‘yaman dedingizmi?" },
    { "text": "Har safar bosganingizda bitta kruassan yig‘laydi." },
    { "text": "Klik, klik, klik... Boshqa ishingiz yo‘qmi?" },
    { "text": "Yana bir marta bosing, balki mo‘jiza ro‘y berar." },
    { "text": "Sichqoncha charchadi, siz-chi?" },
    { "text": "Logotipga tikilib o‘tirish ish vaqtiga kirmaydi." },
    { "text": "Bosmang, qiti g‘im kelyapti." },
    { "text": "Tizim ishlayapti, siz esa shunchaki o‘ynayapsiz." },
    { "text": "Agar shunchalik tez ishlasangiz edi..." },
    { "text": "Bu yerda syurpriz yo‘q, bekorga bosmang." },
    { "text": "Barmoqlaringiz mashq qilyaptimi?" },
    { "text": "Logotip sizni kuzatmoqda." },
    { "text": "To‘xtang! Yana bosish pullik." },
    { "text": "Sizning bu harakatingiz serverni hayron qoldirdi." },
    { "text": "Xatolik 404: Sizning xohishingiz topilmadi." },
    { "text": "Bu dastur o‘zi ishlaydi, siz shunchaki tomoshabinsiz." },
    { "text": "Serverlarimiz ham dam olishni xohlaydi." },
    { "text": "Sabr tagi — sariq oltin emas, shunchaki kutish." },
    { "text": "Tizimni ayblamang, hayot shunaqa." },
    { "text": "Bizda hamma narsa bor, faqat vaqt yo‘q." },
    { "text": "Hozir yuklanmoqda... xuddi dushanba kungi miyangiz kabi." },
    { "text": "Agar bu xato bo‘lsa, demak shunday bo‘lishi kerak edi." },
    { "text": "Ma'lumotlar qayta ishlanmoqda... iltimos, uxlamang." },
    { "text": "Yaxshi xodim tizimni buzmaydi." },
    { "text": "Sizning so‘rovingiz koinotga yuborildi." },
    { "text": "Ctrl+Z hayotda ishlamaydi, afsus." },
    { "text": "Qaniydi hamma narsa pishiriqdek oson bo‘lsa." },
    { "text": "Hozircha hammasi joyida. Hozircha." },
    { "text": "Men sun'iy intellektman, lekin sizning mantiqingizni tushunmadim." },
    { "text": "Ertaga balki uyg‘onmassiz." }
]